[build-system]
requires = ["setuptools", "setuptools_scm"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "src/wattleflow/core/_version.py"


[project]
name = "wattleflow"
version="0.0.0.28"
description = "Wattleflow Core for Python"
readme = "README.md"
license = { file = "LICENSE" }
authors = [{ name = "wattleflow", email = "wattleflow@outlook.com" }]
keywords = ["wattleflow", "framework", "core", "library", "design", "patterns", "python", "library", "software engineering"]
requires-python = ">=3.8"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Operating System :: OS Independent",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Libraries",
]

[project.urls]
homepage = "https://github.com/wattleflow/core.git"
repository = "https://github.com/wattleflow/core.git"
documentation = "https://github.com/wattleflow/docs.git"

[tool.setuptools]
package-dir = {"" = "src"}  
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]

[tool.black]
line-length = 100
target-version = ['py38']
