# Module name: core/__init__.py
# Author: (wattleflow@outlook.com)
# Copyright: © 2022–2026 WattleFlow. All rights reserved.
# License: Apache 2 Licence

# NOTE (ORG-03): role TypeVars (Action, Result, Element, Item, ...) are
# module-scoped and deliberately NOT re-exported here — several modules
# declare the same role name for their own contracts (e.g. Result in
# behavioural, concurrent and transactional), so a package-level re-export
# would silently shadow all but one. Import roles from their defining
# module: `from wattleflow.core.transactional import Item`.

from .behavioural import (
    IAsyncAggregate,
    IAsyncIterator,
    IColleague,
    ICommand,
    IElement,
    IExpression,
    IHandler,
    IInvoker,
    IIterator,
    ILogger,
    IMediator,
    IMemento,
    IObservable,
    IObserver,
    IOriginator,
    IState,
    IStateContext,
    IStateMachine,
    IStrategy,
    IStrategyContext,
    ISyncAggregate,
    ITemplate,
    IVisitor,
)
from .concurrent import (
    IActor,
    IBarrier,
    IBSPSystem,
    ICallback,
    ICoroutine,
    IDataParallelTask,
    IDivideAndConquer,
    IEventLoop,
    IForkJoinPool,
    IForkJoinTask,
    IFuture,
    IGraphProcessing,
    IMapper,
    IMessageQueue,
    IObservableReactive,
    IObserverReactive,
    IPromise,
    IPublisher,
    IReducer,
    ISPMDProgram,
    IStencil,
    ISubscriber,
    ISuperstep,
    ISystem,
    IThreadPool,
    IWorker,
    IWorkStealingScheduler,
)
from .creational import (
    IBuilder,
    ICreator,
    IFactory,
    IProduct,
    IPrototype,
)
from .framework import (
    IWattleflow,
)
from .structural import (
    IAbstraction,
    IAdaptee,
    IAdapter,
    IComponent,
    IComposite,
    IDecorator,
    IFacade,
    IFlyweight,
    IFlyweightFactory,
    IImplementor,
    IProxy,
    ITarget,
)
from .transactional import (
    IBlackboard,
    IDocument,
    IDriver,
    IEvent,
    IEventListener,
    IEventSource,
    IFormatter,
    IModule,
    IParser,
    IPipeline,
    IProcessor,
    IQuery,
    IRepository,
    ISaga,
    IScheduler,
    ISignal,
    IUnitOfWork,
)

__all__ = [
    "IAbstraction",
    "IActor",
    "IAdaptee",
    "IAdapter",
    "IAsyncAggregate",
    "IAsyncIterator",
    "IBSPSystem",
    "IBarrier",
    "IBlackboard",
    "IBuilder",
    "ICallback",
    "IColleague",
    "ICommand",
    "IComponent",
    "IComposite",
    "ICoroutine",
    "ICreator",
    "IDataParallelTask",
    "IDecorator",
    "IDivideAndConquer",
    "IDocument",
    "IDriver",
    "IElement",
    "IEvent",
    "IEventListener",
    "IEventLoop",
    "IEventSource",
    "IExpression",
    "IFacade",
    "IFactory",
    "IFlyweight",
    "IFlyweightFactory",
    "IForkJoinPool",
    "IForkJoinTask",
    "IFormatter",
    "IFuture",
    "IGraphProcessing",
    "IHandler",
    "IImplementor",
    "IInvoker",
    "IIterator",
    "ILogger",
    "IMapper",
    "IMediator",
    "IMemento",
    "IMessageQueue",
    "IModule",
    "IObservable",
    "IObservableReactive",
    "IObserver",
    "IObserverReactive",
    "IOriginator",
    "IParser",
    "IPipeline",
    "IProcessor",
    "IProduct",
    "IPromise",
    "IPrototype",
    "IProxy",
    "IPublisher",
    "IQuery",
    "IReducer",
    "IRepository",
    "ISPMDProgram",
    "ISaga",
    "IScheduler",
    "ISignal",
    "IState",
    "IStateContext",
    "IStateMachine",
    "IStencil",
    "IStrategy",
    "IStrategyContext",
    "ISubscriber",
    "ISuperstep",
    "ISyncAggregate",
    "ISystem",
    "ITarget",
    "ITemplate",
    "IThreadPool",
    "IUnitOfWork",
    "IVisitor",
    "IWattleflow",
    "IWorkStealingScheduler",
    "IWorker",
]

__author__ = "WattleFlow"
__copyright__ = "© 2022–2026 WattleFlow. All rights reserved"
__license__ = "Apache 2 Licence"
