# Module name: core/__init__.py
# Author: (W@outlook.com)
# Copyright: © 2022–2026 W. All rights reserved.
# License: Apache 2 Licence

from .framework import (
    IWattleflow,
    # var types
    T,
    W,
)

from .behavioral import (
    # var types
    Action,
    Context,
    Result,
    State,
    # interfaces
    IHandler,
    ICommand,
    IInvoker,
    IExpression,
    IIterator,
    ISyncAggregate,
    IAsyncIterator,
    IAsyncAggregate,
    IMediator,
    IColleague,
    IMemento,
    IOriginator,
    IObserver,
    IObservable,
    IState,
    IStateContext,
    IStateMachine,
    IStrategy,
    IStrategyContext,
    ITemplate,
    IVisitor,
    IElement,
    ILogger,
)

from .concurrent import (
    # var types
    Destination,
    Graph,
    Message,
    Key,
    Value,
    # interfaces
    IActor,
    ISystem,
    IFuture,
    IPromise,
    ICallback,
    IObserverReactive,
    IObservableReactive,
    IEventLoop,
    IPublisher,
    ISubscriber,
    IMessageQueue,
    IThreadPool,
    ICoroutine,
    IMapper,
    IReducer,
    ISuperstep,
    IBSPSystem,
    IForkJoinTask,
    IForkJoinPool,
    IBarrier,
    IDivideAndConquer,
    IDataParallelTask,
    IWorkStealingScheduler,
    IWorker,
    IStencil,
    IGraphProcessing,
    ISPMDProgram,
)

from .creational import (
    IFactory,
    IBuilder,
    IProduct,
    ICreator,
    IPrototype,
    ISingleton,
)

from .structural import (
    ITarget,
    IAdaptee,
    IAdapter,
    IImplementor,
    IAbstraction,
    IComponent,
    IComposite,
    IDecorator,
    IFacade,
    IFlyweight,
    IFlyweightFactory,
    IProxy,
)
from .transactional import (
    IDocument,
    IDriver,
    IEvent,
    IEventListener,
    IEventSource,
    IRepository,
    IBlackboard,
    IModule,
    IPipeline,
    IProcessor,
    IQuery,
    ISaga,
    IScheduler,
    ISignal,
    IUnitOfWork,
)

__all__ = [
    # type vars
    "Action",
    "Context",
    "Destination",
    "Result",
    "State",
    "Graph",
    "Message",
    "Key",
    "Value",
    "W",
    "T",
    # interfaces
    "IAbstraction",
    "IActor",
    "IAdaptee",
    "IAdapter",
    "IAsyncIterator",
    "IAsyncAggregate",
    "IBarrier",
    "IBSPSystem",
    "ICallback",
    "ICommand",
    "IColleague",
    "IComponent",
    "IComposite",
    "ICoroutine",
    "IDocument",
    "IDataParallelTask",
    "IDecorator",
    "IDivideAndConquer",
    "IDriver",
    "IElement",
    "IExpression",
    "IEvent",
    "IEventLoop",
    "IEventListener",
    "IEventSource",
    "IForkJoinTask",
    "IForkJoinPool",
    "IFacade",
    "IFlyweight",
    "IFlyweightFactory",
    "IFuture",
    "IHandler",
    "IMapper",
    "IMediator",
    "IMessageQueue",
    "IMemento",
    "IModule",
    "IInvoker",
    "IImplementor",
    "IIterator",
    "IObserver",
    "IObservable",
    "IOriginator",
    "ISyncAggregate",
    "IState",
    "IStateContext",
    "IStateMachine",
    "IStrategy",
    "IStrategyContext",
    "ITemplate",
    "IVisitor",
    "ILogger",
    "IPromise",
    "IObserverReactive",
    "IObservableReactive",
    "IPublisher",
    "ISubscriber",
    "IReducer",
    "ISuperstep",
    "IWorkStealingScheduler",
    "IWorker",
    "IStencil",
    "IGraphProcessing",
    "ISPMDProgram",
    "IFactory",
    "IBuilder",
    "IProduct",
    "ICreator",
    "IPrototype",
    "ISingleton",
    "ITarget",
    "IThreadPool",
    "IProxy",
    "ISystem",
    "IRepository",
    "IBlackboard",
    "IPipeline",
    "IProcessor",
    "IQuery",
    "ISaga",
    "IScheduler",
    "ISignal",
    "IUnitOfWork",
    "IWattleflow",
]

__author__ = "W"
__copyright__ = "© 2022–2026 W. All rights reserved"
